<a href="https://colab.research.google.com/github/vijaivimu/Python-For-Data-Science/blob/main/tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
scalar = torch.tensor(20)

In [5]:
scalar.ndim

0

In [6]:
scalar.shape

torch.Size([])

In [8]:
scalar.item()

20

In [9]:
list = [1,2,3,4,5]

In [10]:
vector = torch.tensor(list)

In [11]:
vector

tensor([1, 2, 3, 4, 5])

In [12]:
vector.shape

torch.Size([5])

In [13]:
vector.ndim

1

In [21]:
vector[0].item()

1

In [22]:
vector + 10

tensor([11, 12, 13, 14, 15])

In [23]:
matrix = torch.tensor([[1,2,3],[4,5,6]])

In [24]:
matrix.shape

torch.Size([2, 3])

In [25]:
matrix.ndim

2

In [26]:
tensor3d = torch.tensor([[[1,2,3],[4,5,6]],[[17,2,3],[18,5,6]]                                        ])

In [27]:
tensor3d.shape

torch.Size([2, 2, 3])

In [32]:
k= torch.rand((3,3,2))

In [33]:
k.shape

torch.Size([3, 3, 2])

In [34]:
k.ndim

3

In [36]:
k.size()

torch.Size([3, 3, 2])

In [44]:
tensordtyp = torch.tensor([1.0,2.0,3.0],dtype=torch.int16)

In [45]:
tensordtyp

tensor([1, 2, 3], dtype=torch.int16)

In [46]:
tensordtyp = torch.tensor([1.0,2.0,3.0],requires_grad=True)

In [47]:
tensordtyp = torch.tensor([1.0,2.0,3.0],requires_grad=True,device='cuda:0')