<a href="https://colab.research.google.com/github/vijaivimu/Python-For-Data-Science/blob/main/tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
scalar = torch.tensor(20)

In [3]:
scalar.ndim

0

In [4]:
scalar.shape

torch.Size([])

In [5]:
scalar.item()

20

In [6]:
list = [1,2,3,4,5]

In [7]:
vector = torch.tensor(list)

In [8]:
vector

tensor([1, 2, 3, 4, 5])

In [9]:
vector.shape

torch.Size([5])

In [10]:
vector.ndim

1

In [11]:
vector[0].item()

1

In [12]:
vector + 10

tensor([11, 12, 13, 14, 15])

In [13]:
matrix = torch.tensor([[1,2,3],[4,5,6]])

In [14]:
matrix.shape

torch.Size([2, 3])

In [15]:
matrix.ndim

2

In [16]:
tensor3d = torch.tensor([[[1,2,3],[4,5,6]],[[17,2,3],[18,5,6]]                                        ])

In [17]:
tensor3d.shape

torch.Size([2, 2, 3])

In [18]:
k= torch.rand((3,3,2))

In [19]:
k.shape

torch.Size([3, 3, 2])

In [20]:
k.ndim

3

In [21]:
k.size()

torch.Size([3, 3, 2])

In [22]:
tensordtyp = torch.tensor([1.0,2.0,3.0],dtype=torch.int16)

In [23]:
tensordtyp

tensor([1, 2, 3], dtype=torch.int16)

In [24]:
tensordtyp = torch.tensor([1.0,2.0,3.0],requires_grad=True)

In [25]:
tensordtyp = torch.tensor([1.0,2.0,3.0],requires_grad=True,device='cuda:0')

In [26]:
tensor1 = torch.rand((2,2))

In [27]:
tensor1 = tensor1.cuda()

In [28]:
tensor2 = torch.rand((2,2))


In [29]:
tensor1 + tensor2

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

In [30]:
tensor2 = tensor2.cuda()

In [31]:
tensor1 + tensor2

tensor([[0.6495, 0.0956],
        [1.2986, 1.0297]], device='cuda:0')

In [32]:
tensor1.cpu() + tensor2.cpu()

tensor([[0.6495, 0.0956],
        [1.2986, 1.0297]])